# 1. Create a 3x3x3 array with random values 

In [1]:
import numpy as np
a = np.random.random((3, 3, 3))
print(a)

[[[0.60318704 0.06058132 0.66275999]
  [0.04785952 0.34899713 0.02457779]
  [0.79104824 0.45813278 0.61359274]]

 [[0.62781296 0.28687792 0.641842  ]
  [0.39798897 0.72609597 0.922925  ]
  [0.75934119 0.58996598 0.08470076]]

 [[0.73830306 0.62009019 0.55627299]
  [0.783975   0.97418868 0.81536986]
  [0.72539967 0.7835494  0.58941317]]]


# 2.Create a 5x5 matrix with values 1,2,3,4 just below the diagonal

In [2]:
a = np.diag(1+np.arange(4), k = -1)
print("Created matrix is:\n{0}\n".format(a))

Created matrix is:
[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]



# 3.Create a 8x8 matrix and fill it with a checkerboard pattern

In [3]:
chkBardArr = np.array([[0, 1] * 4, [1, 0] * 4] * 4)
chkBardArr

array([[0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0]])

# 4. Normalize a 5x5 random matrix

In [4]:
X = np.random.random((5, 5))
X_max, X_min = X.max(), X.min()
X = (X - X_min) / (X_max - X_min)
print("Normalized matrix:\n{0}\n".format(X))

Normalized matrix:
[[0.59589961 0.50631844 0.81323289 0.57151665 0.96495217]
 [1.         0.5906386  0.14363341 0.41632417 0.6583923 ]
 [0.0052344  0.84950577 0.84427839 0.57401499 0.21591029]
 [0.27687446 0.42905837 0.888593   0.75971575 0.3764823 ]
 [0.04062083 0.9180296  0.53255466 0.         0.08089899]]



# 5.  How to find common values between two arrays?

In [5]:
a = np.random.randint(1, 170, (1, 50))
print("array a is:\n{0}\n".format(a))

b = np.random.randint(1, 170, (1, 70))
print("array b is:\n{0}\n".format(b))

print("Intersect of the two array:\n{0}\n".format(np.intersect1d(a, b)))

array a is:
[[105  51  80  71  73 111 147  30  93  71  33  20  22 155   8 151 131 120
  100  39  60 138  66  78  94 114  51 124 124  62 151  29 116 121  87  95
  153  61 130 107  23 162 108  98  92   8   5  55 159  86]]

array b is:
[[ 39  84  81   1 141   9  52 158  83 149 116 116 103 109  96 134  15 104
   96  76  19  52 108 151 166  26 135  20 142 110 142  83 164  49  91  94
  111  83 109 153  92  37  92  69 155  15  43 105  90  26 149 151  13  37
   63 110  18  88  49  23  85 119  14  59  67 101 155  64   5  34]]

Intersect of the two array:
[  5  20  23  39  92  94 105 108 111 116 151 153 155]



# 6.How to get the dates of yesterday, today and tomorrow?

In [6]:
print("Yesterday is:\t{0}\n".format(np.datetime64('today', 'D') - np.timedelta64(1, 'D')))
print("Today is:\t{0}\n".format(np.datetime64('today', 'D')))
print("Tomorrow is:\t{0}\n".format(np.datetime64('today', 'D') + np.timedelta64(1, 'D')))

Yesterday is:	2020-07-26

Today is:	2020-07-27

Tomorrow is:	2020-07-28



# 7. Consider two random array A and B, check if they are equal

In [7]:
a = np.random.randint(1, 200, (1, 90))
b = np.random.randint(1, 200, (1, 80))
print("Array-1 is:\n{0}\n".format(a))
print("Array-2 is:\n{0}\n".format(b))
print("Does the arrays are equal: {0}".format(np.array_equal(a, b)))

Array-1 is:
[[137   4 153  45 109 106 153 121 163 175  98 143 163  88  63 104 116 176
   77  25  33 155 179   6  75  83 171  99 140  41 120  97  93 108  59  14
    8  84  91 122 199  33   6   4 123 143  24  72  18  56  87 129  80  48
  134 156  10  26  16 163 166 111 170  71  82 103 167  26 125  21  98  56
  129 108  23  81  65   7 106  73  15  14  25 111  97 117 130 122 196 159]]

Array-2 is:
[[ 44  72 183 108  91  96  10  35 193 171 132 178 142   6 155 110  48 193
   31  79 124 120  88  76 177 102  41 135 106  43 134  66  77 131  12 126
  103 166 132 101 137  78  51  68 189 122  65 162 123  31 117 190  15  81
   80 168 192 125 118  68 175 173 172  89 103  93  48  25  49  47  45  19
   25 103  26  38 159  76 142 151]]

Does the arrays are equal: False


# 8.Create random vector of size 10 and replace the maximum value by 0 

In [8]:
va = np.random.randint(1, 90, (1, 10))

print("Input Vector:\t{0}\n".format(va))
idx = np.ma.argmax(va)
va[0][idx] = 0
print("Replaced index {0} in out array:\t{1}\n".format(idx, va))

Input Vector:	[[47 28 71 48 13  6 27 64 27 56]]

Replaced index 2 in out array:	[[47 28  0 48 13  6 27 64 27 56]]



# 9. How to print all the values of an array?

In [9]:
import sys
np.set_printoptions(threshold=sys.maxsize)
X = np.zeros((50, 50))
print(X)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.

# 10.Subtract the mean of each row of a matrix

In [10]:
X = np.random.random((5, 6))
print("Original Matrix:\n{0}\n".format(X))

Z = X - X.mean(axis=1).reshape(-1, 1)
print("Normalized with mean substraction:\n{0}\n".format(Z))

Original Matrix:
[[0.4585952  0.85911751 0.92692787 0.59603957 0.61216268 0.22894355]
 [0.97386349 0.11889903 0.7251818  0.15308984 0.81945039 0.44292439]
 [0.30824619 0.50299763 0.20833469 0.50746253 0.49061749 0.98737993]
 [0.17953374 0.30499498 0.15331381 0.98869406 0.68760282 0.97733038]
 [0.63561391 0.63121409 0.39175136 0.9404714  0.75980567 0.84247717]]

Normalized with mean substraction:
[[-0.15503586  0.24548645  0.31329681 -0.0175915  -0.00146839 -0.38468752]
 [ 0.434962   -0.42000246  0.18628031 -0.38581165  0.2805489  -0.0959771 ]
 [-0.19259355  0.00215788 -0.29250506  0.00662279 -0.01022225  0.48654019]
 [-0.36904455 -0.24358332 -0.39526449  0.44011576  0.13902452  0.42875208]
 [-0.06460835 -0.06900817 -0.30847091  0.24024913  0.0595834   0.14225491]]



# 11.Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? 

In [11]:
A = np.ones(10)
B = np.random.randint(0, len(A), 15)
np.add.at(A, B, 1)
print("Adding 1 to the indices: ({0}) is:\t{1}".format(B, A))

Adding 1 to the indices: ([9 2 3 9 3 2 0 2 8 0 4 5 0 7 9]) is:	[4. 1. 4. 3. 2. 2. 1. 2. 2. 4.]


# 12.How to get the diagonal of a dot product?

In [12]:
X = np.random.randint(1, 60, (5, 5))
Y = np.random.randint(1, 70, (5, 5))

In [13]:
print("Diagonal of Dot Product:\t{0}\n".format(np.diag(np.dot(X, Y))))

Diagonal of Dot Product:	[8625 7301 8650 1591 8036]



In [14]:
print("Diagonal Dot product:\t{0}".format(np.sum(X * Y.T, axis=1)))

Diagonal Dot product:	[8625 7301 8650 1591 8036]


# 13.How to find the most frequent value in an array?

In [15]:
X = np.random.randint(5, 190, 90)
print(X)
print("Most Frequent:{0}".format(np.bincount(X).argmax()))

[  8 182  53 166 174  39  85 169   8  88  38  52 106  67 113   8  56  49
  35  11  28 139  79 179 109 118 173  25 167 161  43  15  22  55 128  80
 126  81  11  61 122 150  14 154 124 182 151   7  35  94  21 188 135 136
  69 103  57  48  13  51  93  14  28  25 127 127  66 140 189  64  67 120
 160  89 124  34 126  65 168  53  53  94 134  30 119 187  73 161 159  49]
Most Frequent:8


# 14.How to get the n largest values of an array

In [16]:
X = np.random.randint(1, 100000, 15000)
np.random.shuffle(X)
n = 9

In [17]:
sorted(X, reverse=True)[:n]

[99998, 99997, 99996, 99993, 99986, 99984, 99981, 99980, 99974]

In [18]:
np.sort(X, kind="heapsort")[-n:]

array([99974, 99980, 99981, 99984, 99986, 99993, 99996, 99997, 99998])

# 15.How to create a record array from a regular array?

In [19]:
X = np.random.random((6, 8))

In [20]:
R = np.core.records.fromarrays(X.T)
print("Record array is:\n{0}\n".format(R))

Record array is:
[(0.35382855, 0.81016672, 0.11473247, 0.19397204, 0.74672418, 0.82672077, 0.50017708, 0.94994567)
 (0.26664171, 0.40242874, 0.56681426, 0.23593174, 0.47623053, 0.19261306, 0.32109003, 0.21838039)
 (0.12709942, 0.54232525, 0.82423322, 0.63683423, 0.28283951, 0.14106616, 0.73416025, 0.52676703)
 (0.36354641, 0.46739533, 0.14111318, 0.30867618, 0.84578393, 0.66157919, 0.40909695, 0.08614243)
 (0.9453629 , 0.89567752, 0.74946939, 0.90152913, 0.64145084, 0.39221693, 0.04256026, 0.30850355)
 (0.94034787, 0.69200647, 0.42610008, 0.99269276, 0.22589826, 0.16478177, 0.16107442, 0.21373406)]

